HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=50000
setopt autocd extendedglob nomatch notify
unsetopt beep
bindkey -v
zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit
compinit
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
export EDITOR=/usr/bin/vim
export SYSTEMD_EDITOR=/usr/bin/vim
alias ls="ls --color"
alias ll="ls --color --group-directories-first -lh"
alias la="ls --color -lhd .*"
alias grep="grep --color"