{
 "title": "Homelab Power Monitoring",
 "description": "Power monitoring dashboard",
 "tags": [
  "Power",
  "env"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Device", "query": { "query": "label_values(shp_device)" } }
  ]
 },
 "panels": [
  {
   "title": "Relay State: $Device",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "relay1_state{shp_device=\"$Device\", job=\"SHP10\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy_power_kilowatts_daily{shp_device=\"$Device\", job=\"SHP10\"}"
    }
   ]
  },
  {
   "title": "Active Power: $Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "energy_power_active_watts{shp_device=\"$Device\", job=\"SHP10\"}"
    }
   ]
  },
  {
   "title": "Apparent & Reactive Power: $Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    {
     "expr": "tasmota_sensors_apparentpower_{shp_device=\"$Device\"}",
     "legendFormat": "Apparent Power (VA)"
    },
    {
     "expr": "tasmota_sensors_reactivepower_{shp_device=\"$Device\"}",
     "legendFormat": "Reactive Power (VAr)"
    }
   ]
  },
  {
   "title": "Voltage & Current: $Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "tasmota_sensors_voltage_volts{shp_device=\"$Device\"}",
     "legendFormat": "Volts (V)"
    },
    {
     "expr": "tasmota_sensors_current_amperes{shp_device=\"$Device\"}",
     "legendFormat": "Amperes (A)"
    }
   ]
  },
  {
   "title": "Power Factor & Temperature: $Device ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasmota_sensors_factor_{shp_device=\"$Device\"}",
     "legendFormat": "Power factor (cosϕ)"
    },
    {
     "expr": "tasmota_sensors_temperature_celsius{shp_device=\"$Device\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  }
 ]
}