---
- name: Enable corosync service
  ansible.builtin.systemd:
    name: corosync.service
    enabled: yes

- name: Restart corosync service
  ansible.builtin.systemd:
    name: corosync.service
    state: restarted

- name: Enable pacemaker service
  ansible.builtin.systemd:
    name: pacemaker.service
    enabled: yes

- name: Restart pacemaker service
  ansible.builtin.systemd:
    name: pacemaker.service
    state: restarted