{
 "title": "Stork Kea DHCPv4",
 "tags": [
  "kea",
  "stork",
  "dhcp4",
  "prometheus",
  "network"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "kea_dhcp4_packets_received_total"
    }
   },
   { "name": "subnet", "label": "Subnet", "query": { "query": "kea_dhcp4_addresses_total" } }
  ]
 },
 "panels": [
  {
   "title": "Number of drops of received packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp4_packets_received_total{operation=\"drop\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Actual number of DORA  packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp4_packets_received_total{operation=\"discover\", instance=~\"$instance\"} or kea_dhcp4_packets_sent_total{operation=\"offer\", instance=~\"$instance\"}\nor kea_dhcp4_packets_received_total{operation=\"request\", instance=~\"$instance\"} or kea_dhcp4_packets_sent_total{operation=\"ack\", instance=~\"$instance\"}",
     "legendFormat": "{{operation}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of sent NAKs ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp4_packets_sent_total{operation=\"nak\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total number of addresses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of addresses assigned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_assigned_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Subnet utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * kea_dhcp4_addresses_assigned_total{instance=~\"$instance\", subnet=~\"$subnet\"} / kea_dhcp4_addresses_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of reclaimed addresses per 10min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kea_dhcp4_addresses_reclaimed_total{instance=~\"$instance\", subnet=~\"$subnet\"}[10m])",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of addresses declined",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_declined_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of addresses declined-reclaimed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_declined_reclaimed_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Subnet address utilization (server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "storkserver_subnet_address_utilization{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\""
    }
   ]
  },
  {
   "title": "Shared network address utilization (server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "storkserver_shared_network_address_utilization{instance=~\"$instance\"}",
     "legendFormat": "subnet \"{{name}}\""
    }
   ]
  },
  {
   "title": "Machines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storkserver_auth_unauthorized_machine_total{instance=~\"$instance\"}",
     "legendFormat": "unauthorized on {{instance}}"
    },
    {
     "expr": "storkserver_auth_authorized_machine_total{instance=~\"$instance\"}",
     "legendFormat": "authorized on {{instance}}"
    },
    {
     "expr": "storkserver_auth_unreachable_machine_total{instance=~\"$instance\"}",
     "legendFormat": "unreachable on {{instance}}"
    }
   ]
  }
 ]
}