---
- name: Open wireguard firewalld port
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone }}"
    port: 51820/udp
    permanent: yes
    immediate: yes
    state: enabled

- name: Get pacemaker current configuration
  ansible.builtin.command:
    cmd: crm configure show
  register: pacemaker_conf
  changed_when: no
  run_once: yes

- name: Configure wireguard pacemaker ressource
  ansible.builtin.command:
    cmd: "crm configure primitive wireguard_{{ item.wireguard }}_HA systemd:wg-quick@{{ item.wireguard }} op monitor interval=10s"
  when: "'primitive wireguard_' + item.wireguard + '_HA' not in pacemaker_conf.stdout"
  run_once: yes
  loop: "{{ wireguard_confs }}"
  loop_control:
    label: "{{ item.wireguard }}"

- name: Configure wireguard colocation with VIPs
  ansible.builtin.command:
    cmd: "crm configure colocation wireguard_{{ item.wireguard }}_VIP inf: wireguard_{{ item.wireguard }}_HA virtual_IP4 virtual_IP6"
  when: "'colocation wireguard_' + item.wireguard + '_VIP inf:' not in pacemaker_conf.stdout"
  run_once: yes
  loop: "{{ wireguard_confs }}"
  loop_control:
    label: "{{ item.wireguard }}"
